SSAFY-6th-Algorithm/algorithm-study

src/공윤환/week3/BJ_1068.java, src/공윤환/week3/BJ_11559.java, src/공윤환/week3/BJ_1339.java, src/공윤환/week3/BJ_1697.java, src/공윤환/week3/BJ_5639.java
=> [윤환] week3

src/공윤환/week3/BJ_1068.java, src/공윤환/week4/BJ_1052.java, src/공윤환/week4/BJ_13904.java, src/공윤환/week4/BJ_14500.java, src/공윤환/week4/BJ_1759.java, src/공윤환/week4/BJ_1992.java
=> [윤환] week4

src/강동석/week4/Baekjoon_1052.java, src/강동석/week4/Baekjoon_13904.java, src/강동석/week4/Baekjoon_14500.java, src/강동석/week4/Baekjoon_1759.java, src/강동석/week4/Baekjoon_1992.java
=> UPDATE dongseok week4

src/강동석/week5/Baekjoon_11657.java, src/강동석/week5/Baekjoon_17144.java, src/강동석/week5/Baekjoon_1753.java, src/강동석/week5/Baekjoon_1774.java, src/강동석/week5/Baekjoon_4386.java
=> UPDATE 강동석 week5

src/강동석/week6/Baekjoon_14503.java, src/강동석/week6/Baekjoon_17471.java, src/강동석/week6/Baekjoon_1941.java
=> [동석] week6

src/공윤환/week6/BJ_14503.java, src/공윤환/week6/BJ_17471.java, src/공윤환/week6/BJ_17472.java, src/공윤환/week6/BJ_1941.java
=> [윤환] week6

src/김현지/week7/p60059.java, src/김현지/week7/p67255.java, src/김현지/week7/p72412.java
=> [현지] week7

src/공윤환/week7/PG_42891.java, src/공윤환/week7/PG_60059.java, src/공윤환/week7/PG_67256.java, src/공윤환/week7/PG_72412.java
=> [윤환] week7

src/강동석/week6/Baekjoon_17472.java, src/강동석/week7/Programmers_60059.java, src/강동석/week7/Programmers_67256.java, src/강동석/week7/Programmers_72412.java
=> week7 dongseok

src/강동석/week6/Baekjoon_1162.java, src/강동석/week7/Programmers_42891.java, src/강동석/week8/Baekjoon_12865.java, src/강동석/week8/Baekjoon_17070.java, src/강동석/week8/Programmers_17676.java, src/강동석/week8/Programmers_64062.java
=> [동석] week8

src/공윤환/week6/BJ_1162.java, src/공윤환/week7/PG_72412.java, src/공윤환/week8/BJ_12865.java, src/공윤환/week8/BJ_17070.java, src/공윤환/week8/PG_17676.java, src/공윤환/week8/PG_64062.java
=> [윤환] week8

src/이정수/week4/물병_1052.java, src/이정수/week4/암호만들기_1759.java, src/이정수/week4/쿼드트리_1992.java, src/이정수/week4/테크로미노_14500.java, src/이정수/week6/다리만들기2_17472.java, src/이정수/week7/무지의먹방라이브_42891.java, src/이정수/week7/순위검색_72412.java, src/이정수/week7/자물쇠와열쇠_60059.java, src/이정수/week7/키패드누르기_67256.java, src/이정수/week8/징검다리건너기_64062.java, src/이정수/week8/추석트래픽_17676.java, src/이정수/week8/파이프옮기기1_17070.java, src/이정수/week8/평범한배낭_12865.java
=> [정수] week7

src/공윤환/week9/BJ_14719.java, src/공윤환/week9/BJ_1707.java, src/공윤환/week9/BJ_21611.java, src/공윤환/week9/PG_60062.java, src/공윤환/week9/PG_60063.java
=> [윤환] week9

src/강동석/week9/Baekjoon_14719.java, src/강동석/week9/Baekjoon_1707.java, src/강동석/week9/Baekjoon_21611.java, src/강동석/week9/Programmers_60062.java
=> week9 dongseok

src/강동석/week13/Baekjoon_20002.java, src/강동석/week13/Programmers_17678.java, src/강동석/week13/Programmers_64064.java
=> [동석]week13

src/공윤환/week13/BJ_20002.java, src/공윤환/week13/PG_17678.java, src/공윤환/week13/PG_64064.java
=> [윤환] week13

src/강동석/week14/Baekjoon_13459.java, src/강동석/week14/Baekjoon_3980.java, src/강동석/week14/Programmers_42892.java
=> [동석]week14

src/강동석/week11/Baekjoon_19237.java, src/강동석/week15/Baekjoon_1245.java, src/강동석/week15/Programmers_17687.java, src/강동석/week15/Programmers_42893.java, src/강동석/week15/Solution1865_강동석.java, src/강동석/week15/Solution2382_강동석.java, src/강동석/week15/Solution5658_강동석.java
=> [동석]week15

src/공윤환/week14/PG_60061.java, src/공윤환/week15/BJ_1245.java, src/공윤환/week15/PG_17687.java, src/공윤환/week15/PG_42893.java, src/공윤환/week15/SWEA_1865.java, src/공윤환/week15/SWEA_2382.java, src/공윤환/week15/SWEA_2383.java, src/공윤환/week15/SWEA_5658.java
=> [윤환] week15

src/공윤환/week16/BJ_1520.java, src/공윤환/week16/BJ_20058.java, src/공윤환/week16/PG_42888.java
=> [윤환] week16

src/강동석/week15/Solution2383_강동석.java, src/강동석/week16/Baekjoon_1520.java, src/강동석/week16/Baekjoon_20058.java, src/강동석/week16/Programmers_42888.java
=> [동석] ADD week16

src/강동석/week17/Baekjoon_10282.java, src/강동석/week17/Baekjoon_2467.java, src/강동석/week17/Programmers_1832.java, src/강동석/week17/Programmers_81303.java
=> [동석]week17

src/김도현/week17(211227)/BJ10282.java, src/김도현/week17(211227)/BJ2467.java, src/김도현/week17(211227)/PG1832.java, src/김도현/week17(211227)/PG81303.java
=> [도현] week17

src/공윤환/week17/BJ_10282.java, src/공윤환/week17/BJ_2467.java, src/공윤환/week17/PG_1832.java, src/공윤환/week17/PG_81303.java
=> [윤환] week17

src/강동석/week18/Baekjoon_1005.java, src/강동석/week18/Baekjoon_1238.java, src/강동석/week18/Baekjoon_14499.java, src/강동석/week18/Baekjoon_16637.java
=> [동석]week18

src/김도현/week18(220103)/BJ1005.java, src/김도현/week18(220103)/BJ1238.java, src/김도현/week18(220103)/BJ14499.java, src/김도현/week18(220103)/BJ16637.java
=> [도현]week18

src/공윤환/week19/BG_2212.java, src/공윤환/week19/BJ_13460.java, src/공윤환/week19/BJ_17281.java, src/공윤환/week19/BJ_2110.java, src/공윤환/week19/PG_64065.java
=> [윤환] week 19

src/김도현/week19(220110)/BJ13460.java, src/김도현/week19(220110)/BJ17281.java, src/김도현/week19(220110)/BJ2110.java, src/김도현/week19(220110)/BJ2212.java, src/김도현/week19(220110)/PG64065.java, src/김도현/week20(220117)/BJ2533.java, src/김도현/week20(220117)/PG17683.java, src/김도현/week20(220117)/bj1062.java, src/김도현/week20(220117)/bj1300.java, src/김도현/week20(220117)/bj16234.java
=> [도현]week19

src/강동석/week14/Programmers_60061.java, src/강동석/week19/Baekjoon_13460.java, src/강동석/week19/Baekjoon_17281.java, src/강동석/week19/Baekjoon_2110.java, src/강동석/week19/Baekjoon_2212.java, src/강동석/week19/Programmers_64065.java
=> [동석]week19

src/공윤환/week20/BJ_1062.java, src/공윤환/week20/BJ_1300.java, src/공윤환/week20/BJ_16234.java, src/공윤환/week20/BJ_2533.java, src/공윤환/week20/PG_17683.java
=> [윤환] week20

src/강동석/week20/Baekjoon_1062.java, src/강동석/week20/Baekjoon_1300.java, src/강동석/week20/Baekjoon_16234.java, src/강동석/week20/Baekjoon_2533.java, src/강동석/week20/Programmers_17683.java
=> [동석] week20

src/강동석/week21/Baekjoon_11085.java, src/강동석/week21/Baekjoon_1700.java, src/강동석/week21/Baekjoon_17136.java, src/강동석/week21/Baekjoon_4811.java, src/강동석/week21/Programmers_17686.java, src/강동석/week22/Baekjoon_1197.java, src/강동석/week22/Baekjoon_12851.java, src/강동석/week22/Baekjoon_14950.java, src/강동석/week22/Baekjoon_2933.java, src/강동석/week22/Programmers_17677.java
=> [동석] week21

src/김도현/week23(220221)/BJ1043.java, src/김도현/week23(220221)/BJ1194.java, src/김도현/week23(220221)/PG42842.java, src/김도현/week23(220221)/PG43238.java, src/김도현/week23(220221)/PG84021.java
=> [도현]week23

src/공윤환/week24/BJ_20055.java, src/공윤환/week24/BJ_2616.java, src/공윤환/week24/PG_42885.java, src/공윤환/week24/PG_72411.java
=> [윤환] week24

src/김도현/week24(220228)/BJ20055.java, src/김도현/week24(220228)/BJ2616.java, src/김도현/week24(220228)/PG42885.java, src/김도현/week24(220228)/PG67259.java, src/김도현/week24(220228)/PG72411.java
=> [도현]week24

src/공윤환/week25/BJ_1107.java, src/공윤환/week25/PG_17684.java, src/공윤환/week25/PG_42578.java, src/공윤환/week25/PG_92343.java
=> [윤환] week 25

src/공윤환/week26/BJ_15684.java, src/공윤환/week26/BJ_2075.java, src/공윤환/week26/PG_42626.java, src/공윤환/week26/PG_92342.java, src/공윤환/week26/PG_92344.java, src/공윤환/week26/SK_ICT/Four.java, src/공윤환/week26/SK_ICT/One.java, src/공윤환/week26/SK_ICT/Three.java, src/공윤환/week26/SK_ICT/Two.java
=> [윤환] week26

src/김도현/week26(220314)/BJ15684.java, src/김도현/week26(220314)/BJ2075.java, src/김도현/week26(220314)/PG42626.java, src/김도현/week26(220314)/PG92342.java, src/김도현/week26(220314)/PG92344.java
=> [도현]week26

src/공윤환/week27/BJ_10026.java, src/공윤환/week27/BJ_1012.java, src/공윤환/week27/BJ_14501.java, src/공윤환/week27/BJ_2473.java, src/공윤환/week27/BJ_5567.java
=> [윤환] week27

src/임형준/week28/마법사상어와비바라기/Main.java, src/임형준/week28/점프/Main.java, src/임형준/week28/최소값찾기/Main.java
=> [형준] week 28

src/공윤환/week28/BJ_11003.java, src/공윤환/week28/BJ_1890.java, src/공윤환/week28/BJ_21610.java
=> [윤환] week28

src/김도현/week28(220328)/BJ12912.java, src/김도현/week28(220328)/BJ1890.java, src/김도현/week28(220328)/BJ20500.java
=> [도현] week28

src/강동석/week30/Baekjoon_14889.java, src/강동석/week30/Baekjoon_16235.java, src/강동석/week30/Baekjoon_16946.java, src/강동석/week30/Baekjoon_4991.java, src/강동석/week30/Programmers_81302.java
=> [동석]week30

src/공윤환/week30/BG_16235.java, src/공윤환/week30/BJ_14889.java, src/공윤환/week30/BJ_16946.java, src/공윤환/week30/BJ_4991.java, src/공윤환/week30/PG_81302.java
=> [윤환] week30

src/임형준/week30/거리두기확인하기/Main.java, src/임형준/week30/로봇청소기/Main.java, src/임형준/week30/벽부수고이동하기4/Main.java, src/임형준/week30/스타트와링크/Main.java
* 나무 재테크는 아직 못 풀었습니다
* 벽부수고 이동하기4와 로봇 청소기는 TLE 때문에 통과를 못했습니다.
=> [형준] week 30

src/강동석/week31/Baekjoon_1007.java, src/강동석/week31/Baekjoon_11049.java, src/강동석/week31/Baekjoon_14888.java, src/강동석/week31/Baekjoon_15685.java, src/강동석/week31/Baekjoon_2580.java
=> [동석]week31

src/김도현/week30(220411)/BJ16946.java, src/김도현/week30(220411)/BJ4991.java
=> [도현] week30

src/강동석/week32/Baekjoon_16236.java, src/강동석/week32/Baekjoon_17142.java, src/강동석/week32/Baekjoon_19238.java, src/강동석/week32/Baekjoon_1938.java, src/강동석/week32/Baekjoon_20061.java
=> [동석] week32

src/김도현/week34(220523)/BJ10942.java, src/김도현/week34(220523)/BJ2234.java, src/김도현/week34(220523)/BJ9207.java
=> [도현] week34

src/김도현/week35(220530)/BJ1655.java, src/김도현/week35(220530)/BJ1912.java
=> [도현] week35

src/신홍철/week31/BOJ_1007/Main.java, src/신홍철/week31/BOJ_11049.java, src/신홍철/week31/BOJ_14888/Main.java, src/신홍철/week31/BOJ_15685/Main.java, src/신홍철/week31/BOJ_2578_빙고.java
=> [홍철]week31

src/김도현/week36(220613)/BJ12026.java, src/김도현/week36(220613)/BJ1946.java, src/김도현/week36(220613)/BJ5430.java
=> [도현] week36

src/강동석/week34/Baekjoon_10942.java, src/강동석/week34/Baekjoon_2234.java, src/강동석/week34/Baekjoon_3085.java, src/강동석/week34/Baekjoon_9207.java
=> [동석]week34

src/김도현/week37(220620)/BJ18870.java, src/김도현/week37(220620)/BJ2631.java, src/김도현/week37(220620)/BJ2805.java
=> [도현] week37
